version: "3"

services:
  bot:
    build: ./bot
    restart: always
    network_mode: bridge
    depends_on:
      - mongodb
      - auth_api
    env_file: .env

  auth_api:
    build: ./auth_api
    restart: always
    network_mode: bridge
    depends_on:
      - mongodb
    env_file: .env
    ports:
    - "5000:5000"


  mongodb:
    restart: always
    image: mongo:latest
    network_mode: bridge
    env_file: .env
    volumes:
    - ./mongo/data/db:/data/db
    ports:
    - "27017:27017"
