from app.utils.keyboards import get_markup
from .buttons import (
    TWITTER_UNAUTHORIZED_BUTTONS,
    TWITTER_AUTHORIZED_BUTTONS,
    TWITTER_STREAM_BUTTONS
)


TWITTER_UNAUTHORIZED_MARKUP = get_markup(TWITTER_UNAUTHORIZED_BUTTONS)
TWITTER_AUTHORIZED_MARKUP = get_markup(TWITTER_AUTHORIZED_BUTTONS)
TWITTER_STREAM_MARKUP = get_markup(TWITTER_STREAM_BUTTONS)
